// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
// #include "driver/uart.h"
// #include "uart.h"
#include <Arduino.h> // log_d
//#include "http_client.h"
//#include "msgpck.h"

// static uint8_t data[BUF_SIZE] = "Button1 clicked\n";

void onButton1Click(lv_event_t * e)
{
  log_i("Button1 clicked\n");
  //uart_write_bytes(UART_PORT, (const char *) data, 17);
  //msgpck_write_map_header(&http, 2);
}
